
#include <stdio.h>
#include <stddef.h>

#include "osev_common/commo_header.h"
#include "osev_common/excep_code.h"
#include "ExcepMsg.h"

//

/*
typedef struct {
    unsigned int excep_code;
    char *excep_msg;
} excmsg;
 */

//

static const excmsg exception_dict[] = {
    {INVA_PARAM_EXPT, "INVA_PARAM_EXPT"}, // HAND_BASE|0x0001
    {NOT_FOUND_CONTA, "NOT_FOUND_CONTA"}, // HAND_BASE|0x0003
    {DROP_ENTIT_EXPT, "DROP_ENTIT_EXPT"}, // HAND_BASE|0x0005
    {FACTO_QUERY_EXPT, "FACTO_QUERY_EXPT"}, // HAND_BASE|0x0007
    {CREAT_ENTIT_EXPT, "CREAT_ENTIT_EXPT"}, // HAND_BASE|0x0009
    {CREAT_QUERY_EXPT, "CREAT_QUERY_EXPT"}, // HAND_BASE|0x000B
    {INVOK_ENTIT_EXPT, "INVOK_ENTIT_EXPT"}, // HAND_BASE|0x000D
    {SEARC_ENTIT_EXPT, "SEARC_ENTIT_EXPT"}, // HAND_BASE|0x0011
    {INSER_ENTIT_EXPT, "INSER_ENTIT_EXPT"}, // HAND_BASE|0x0013
    {UPDAT_ENTIT_EXPT, "UPDAT_ENTIT_EXPT"}, // HAND_BASE|0x0015
    {ECHO_OBJID_EXPT, "ECHO_OBJID_EXPT"}, // HAND_BASE|0x0017
    {RELOA_LVTP_EXPT, "RELOA_LVTP_EXPT"}, // HAND_BASE | 0x0019
    {LVTP_INTEG_EXPT, "LVTP_INTEG_EXPT"}, // HAND_BASE | 0x001B
    {STATI_BASE_EXPT, "STATI_BASE_EXPT"}, // HAND_BASE | 0x001D
    {LVTP_INFO_EXPT, "LVTP_INFO_EXPT"}, // HAND_BASE | 0x0021
    {CONTA_EXIST_EXPT, "CONTA_EXIST_EXPT"}, // HAND_BASE | 0x0023
    {STATU_AUTH_EXPT, "STATU_AUTH_EXPT"}, // HAND_BASE | 0x0027
    {COMPI_COLLE_EXPT, "COMPI_COLLE_EXPT"}, // HAND_BASE | 0x0029
    {CREAT_COLLE_EXPT, "CREAT_COLLE_EXPT"}, // HAND_BASE | 0x002B
    {LVTP_NOT_FOUND, "LVTP_NOT_FOUND"}, // HAND_BASE | 0x002D
    {RELOA_INVOK_CLANG, "RELOA_INVOK_CLANG"}, // HAND_BASE | 0x0031
    {RELOA_INVOK_EXPT, "RELOA_INVOK_EXPT"}, // HAND_BASE | 0x0033
    {RELOA_INVOK_LIBRA, "RELOA_INVOK_LIBRA"}, // HAND_BASE | 0x0035
    {DROP_INVOK_EXPT, "DROP_INVOK_EXPT"}, // HAND_BASE | 0x0037
    {DROP_INVOK_INHE, "DROP_INVOK_INHE"}, // HAND_BASE | 0x0039
    {PARMS_PARM_EXPT, "PARMS_PARM_EXPT"}, // HAND_BASE | 0x003B
    {COMPI_INVOK_EXPT, "COMPI_INVOK_EXPT"}, // HAND_BASE | 0x003D
    {CREAT_INVOK_EXPT, "CREAT_INVOK_EXPT"}, // HAND_BASE | 0x0041
    {INVOK_NOT_FOUND, "INVOK_NOT_FOUND"}, // HAND_BASE | 0x0043
    {INVOK_INFO_EXPT, "INVOK_INFO_EXPT"}, // HAND_BASE | 0x0045
    {INNER_DATA_EXPT, "INNER_DATA_EXPT"}, // HAND_BASE | 0x0047
    {CLOSE_BASE_EXPT, "CLOSE_BASE_EXPT"}, // HAND_BASE | 0x0049
    {OPEN_BASE_EXPT, "OPEN_BASE_EXPT"}, // HAND_BASE | 0x004D
    {ECHO_BASE_EXPT, "ECHO_BASE_EXPT"}, // HAND_BASE | 0x0051
    {QUERY_ASTAT_EXPT, "QUERY_ASTAT_EXPT"}, // HAND_BASE | 0x0053
    {ECHO_ABASE_EXPT, "ECHO_ABASE_EXPT"}, // HAND_BASE | 0x0055
    {CREAT_INHER_EXPT, "CREAT_INHER_EXPT"}, // HAND_BASE | 0x0057
    {PARSE_METHO_EXPT, "PARSE_METHO_EXPT"}, // HAND_BASE | 0x0059
    {SAVE_CLASS_EXPT, "SAVE_CLASS_EXPT"}, // HAND_BASE | 0x005B
    // {SET_STATU_EXPT, "SET_STATU_EXPT"},
    {REPLA_INVOK_DECL, "REPLA_INVOK_DECL"}, // HAND_BASE | 0x0061
    {REPLA_INVOK_EXPT, "REPLA_INVOK_EXPT"}, // HAND_BASE | 0x0063
    {SAVE_CLANG_EXPT, "SAVE_CLANG_EXPT"}, // HAND_BASE | 0x0065
    {OPEN_IHAND_EXPT, "OPEN_IHAND_EXPT"}, // HAND_BASE | 0x0067
    {OPEN_OATTR_EXPT, "OPEN_OATTR_EXPT"}, // HAND_BASE | 0x0069
    {OPEN_BATTR_EXPT, "OPEN_BATTR_EXPT"}, // HAND_BASE | 0x0069
    {OBJEC_FILE_EXPT, "OBJEC_FILE_EXPT"}, // HAND_BASE | 0x006B
    {LIST_LVTP_EXPT, "LIST_LVTP_EXPT"}, // HAND_BASE | 0x006D
    {RELOA_COLLE_DECL, "RELOA_COLLE_DECL"}, // HAND_BASE | 0x006F
    {REQUE_VALID_EXPT, "REQUE_VALID_EXPT"}, // HAND_BASE | 0x0071
    {DROP_COLLE_HAND, "DROP_COLLE_HAND"}, // HAND_BASE | 0x0073
    {DROP_INVOK_INTE, "DROP_INVOK_INTE"}, // HAND_BASE | 0x0075
    {DROP_INVOK_HAND, "DROP_INVOK_HAND"}, // HAND_BASE | 0x0077
    {DROP_INVOK_CONTE, "DROP_INVOK_CONTE"}, // HAND_BASE | 0x0079
    {LVTP_INHER_EXPT, "LVTP_INHER_EXPT"}, // HAND_BASE | 0x007B
    {DROP_COLLE_INHE, "DROP_COLLE_INHE"}, // HAND_BASE | 0x007F
    {DROP_COLLE_OEXI, "DROP_COLLE_OEXI"}, // HAND_BASE | 0x0081
    {RELOA_INVOK_PROTE, "RELOA_INVOK_PROTE"}, // HAND_BASE | 0x0083
    {RELOA_INVOK_INTEG, "RELOA_INVOK_INTEG"}, // HAND_BASE | 0x0085
    {RELOA_INVOK_DECL, "RELOA_INVOK_DECL"}, // HAND_BASE | 0x0087
    {CREAT_REGIS_INHE, "CREAT_REGIS_INHE"}, // HAND_BASE | 0x0089
    {FIND_SUPER_EXPT, "FIND_SUPER_EXPT"}, // HAND_BASE | 0x008B
    {CONVE_INLVO_EXPT, "CONVE_INLVO_EXPT"}, // HAND_BASE | 0x008D
    {CREAT_INLVO_EXPT, "CREAT_INLVO_EXPT"}, // HAND_BASE | 0x008F
    {SEARC_QUERY_EXPT, "SEARC_QUERY_EXPT"}, // HAND_BASE | 0x0091
    {DROP_QUERY_EXPT, "DROP_QUERY_EXPT"}, // HAND_BASE | 0x0093
    {UPDAT_QUERY_EXPT, "UPDAT_QUERY_EXPT"}, // HAND_BASE | 0x0095
    {INVOK_QUERY_EXPT, "INVOK_QUERY_EXPT"}, // HAND_BASE | 0x0097
    {INSER_QUERY_EXPT, "INSER_QUERY_EXPT"}, // HAND_BASE | 0x0099
    {REPLA_COLLE_EXPT, "REPLA_COLLE_EXPT"}, // HAND_BASE | 0x009B
    {ECHO_QUERY_EXPT, "ECHO_QUERY_EXPT"}, // HAND_BASE | 0x009D
    {CREAT_LVTME_EXPT, "CREAT_LVTME_EXPT"}, // HAND_BASE | 0x009F
    {CREAT_LVOME_EXPT, "CREAT_LVOME_EXPT"}, // HAND_BASE | 0x00A1
    {LOAD_EXPAND_EXPT, "LOAD_EXPAND_EXPT"}, // HAND_BASE | 0x00A3
    {MALLO_LVTEXP_EXPT, "MALLO_LVTEXP_EXPT"}, // HAND_BASE | 0x00A5
    {STATI_OSEV_EXPT, "STATI_OSEV_EXPT"}, // HAND_BASE | 0x00A7
    {INVA_PARAM_LENG, "INVA_PARAM_LENG"}, // HAND_BASE | 0x00A9
    {FIND_ROLE_EXPT, "FIND_ROLE_EXPT"}, // HAND_BASE | 0xA001
    {ADDI_ROLE_EXPT, "ADDI_ROLE_EXPT"}, // HAND_BASE | 0xA003
    {ROLE_USED_EXPT, "ROLE_USED_EXPT"}, // HAND_BASE | 0xA005
    {DELE_ROLE_EXPT, "DELE_ROLE_EXPT"}, // HAND_BASE | 0xA007
    {DISTI_OBID_EXPT, "DISTI_OBID_EXPT"}, // HAND_BASE | 0xA009
    {LOAD_ROLE_EXPT, "LOAD_ROLE_EXPT"}, // HAND_BASE | 0xA00B
    {REVK_PRIV_EXPT, "REVK_PRIV_EXPT"}, // HAND_BASE | 0xA00D
    {FIND_USER_EXPT, "FIND_USER_EXPT"}, // HAND_BASE | 0xA00F
    {GRAN_PRIV_EXPT, "GRAN_PRIV_EXPT"}, // HAND_BASE | 0xA011
    {DELE_USER_EXPT, "DELE_USER_EXPT"}, // HAND_BASE | 0xA013
    {ADDI_USER_EXPT, "ADDI_USER_EXPT"}, // HAND_BASE | 0xA015
    {REVK_ROLE_EXPT, "REVK_ROLE_EXPT"}, // HAND_BASE | 0xA017
    {GRAN_ROLE_EXPT, "GRAN_ROLE_EXPT"}, // HAND_BASE | 0xA019
    {USER_ROLE_EXIS, "USER_ROLE_EXIS"}, // HAND_BASE | 0xA01B
    {ROLE_PRIV_EXIS, "ROLE_PRIV_EXIS"}, // HAND_BASE | 0xA01D
    {BASE_ADMIN_EXPT, "BASE_ADMIN_EXPT"}, // HAND_BASE | 0xA01F
    {BASE_ECHO_EXPT, "BASE_ECHO_EXPT"}, // HAND_BASE | 0xA021
    {BASE_SETLV_EXPT, "BASE_SETLV_EXPT"}, // HAND_BASE | 0xA023
    {BASE_PRIVI_EXPT, "BASE_PRIVI_EXPT"}, // HAND_BASE | 0xA025
    {OSEV_ECHO_EXPT, "OSEV_ECHO_EXPT"}, // HAND_BASE | 0xA027
    {OSEV_SETLV_EXPT, "OSEV_SETLV_EXPT"}, // HAND_BASE | 0xA029
    {OSEV_PRIVI_EXPT, "OSEV_PRIVI_EXPT"}, // HAND_BASE | 0xA02B
    {USER_ROLE_NOTFOUND, "USER_ROLE_NOTFOUND"}, // HAND_BASE | 0xA02D
    {INVA_ATTRIB_EXPT, "INVA_ATTRIB_EXPT"}, // HAND_BASE | 0xA02F
    //
    {0x00, NULL}
};

//
#define STACKBUF_ZLEN 256

const char *excep_stri(int exce_code) {
    static char excstr[STACKBUF_ZLEN];
    char *excep_msg;
    EXCEP_DICTI_VALUE(excep_msg, exception_dict, exce_code)
    if (!excep_msg) {
        sprintf(excstr, "%08X: Unknown exception", exce_code);
        excep_msg = excstr;
    }
    return excep_msg;
}

void excep_echo(char *exce_data, int exce_len) {
    if (sizeof (unsigned int) == exce_len)
        printf("Exception: %s\n", excep_stri(((unsigned int*) exce_data)[0x00]));
    else printf("Unknown exception!\n");
}