
/* 
 * File:   final_invoke.h
 * Author: James Xu
 *
 * Created on 2023.12.22, AM 10:43
 */

#ifndef FINAL_INVOKE_H
#define FINAL_INVOKE_H

#ifdef __cplusplus
extern "C" {
#endif

    // END_INVOK_RECV_TAB
    void END_INVA_RECV(session *seion);
    void end_invo_post_recv(session *seion);

    // end_invo_list_recv
    void end_invo_statu_list_recv(session *seion);
    void end_invo_statu_stati_recv(session *seion);

    void end_invo_creat_recv(session *seion);
    void end_invo_repla_recv(session *seion);
    void end_invo_drop_recv(session *seion);
    void end_invo_integra_recv(session *seion);
    void end_invo_reload_recv(session *seion);

    //
#define END_INVOK_RECV_TAB { \
    /*POST*/ \
    end_invo_post_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*STATU*/ \
    end_invo_statu_list_recv, end_invo_statu_stati_recv , END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*CREATE*/ \
    end_invo_creat_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*REPLA*/ \
    end_invo_repla_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*DROP*/ \
    end_invo_drop_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*INTEGRA*/ \
    end_invo_integra_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*RELOAD*/ \
    end_invo_reload_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV \
}

    //
    void END_INVA_SEND(session *seion);
    void end_invok_send(session *seion);

#define END_INVOK_SEND_TAB { \
    /*INVO_POST*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_STATU*/ \
    end_invok_send, end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_CREAT*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_REPLA*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_DROP*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_INTEGRA*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*INVO_RELOAD*/ \
    end_invok_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND \
}

#ifdef __cplusplus
}
#endif

#endif /* FINAL_INVOKE_H */

