
/* 
 * File:   final_collect.h
 * Author: James Xu
 *
 * Created on 2023.12.22, AM 10:51
 */

#ifndef FINAL_COLLECT_H
#define FINAL_COLLECT_H

#ifdef __cplusplus
extern "C" {
#endif

    //
    void END_INVA_RECV(session *seion);
    void end_coll_post_recv(session *seion);

    // end_coll_list_recv
    void end_coll_statu_list_recv(session *seion);
    void end_coll_statu_stati_recv(session *seion);

    void end_coll_creat_recv(session *seion);
    void end_coll_repla_recv(session *seion);
    void end_coll_drop_recv(session *seion);
    void end_coll_integra_recv(session *seion);
    void end_coll_reload_recv(session *seion);

    //
#define END_COLLE_RECV_TAB { \
    /*COLE_POST*/ \
    end_coll_post_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_STATU*/ \
    end_coll_statu_list_recv, end_coll_statu_stati_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_CREAT*/ \
    end_coll_creat_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_REPLA*/ \
    end_coll_repla_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_DROP*/ \
    end_coll_drop_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_INTEGRA*/ \
    end_coll_integra_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, \
    /*COLE_RELOAD*/ \
    end_coll_reload_recv, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV, END_INVA_RECV \
}

    //
    void END_INVA_SEND(session *seion);
    void end_colle_send(session *seion);

#define END_COLLE_SEND_TAB { \
    /*COLE_POST*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_STATU*/ \
    end_colle_send, end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_CREAT*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_REPLA*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_DROP*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_INTEGRA*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, \
    /*COLE_RELOAD*/ \
    end_colle_send, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND, END_INVA_SEND \
}




#ifdef __cplusplus
}
#endif

#endif /* FINAL_COLLECT_H */

