
/* 
 * File:   initi_collect.h
 * Author: James Xu
 *
 * Created on 2023.12.22, AM 10:52
 */

#ifndef INITI_COLLECT_H
#define INITI_COLLECT_H

#ifdef __cplusplus
extern "C" {
#endif

    // colle
    unsigned int INIT_INVA_RECV(session *seion, evdata *evdat);
    unsigned int init_coll_post_recv(session *seion, evdata *evdat);
    unsigned int init_coll_statu_recv(session *seion, evdata *evdat);
    unsigned int init_coll_creat_recv(session *seion, evdata *evdat);
    unsigned int init_coll_repla_recv(session *seion, evdata *evdat);
    unsigned int init_coll_drop_recv(session *seion, evdata *evdat);
    unsigned int init_coll_integra_recv(session *seion, evdata *evdat);
    unsigned int init_coll_reload_recv(session *seion, evdata *evdat);

#define INIT_COLLE_RECV_TAB { \
    /*COLE_POST*/ \
    init_coll_post_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_STATU*/ \
    init_coll_statu_recv, init_coll_statu_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_CREAT*/ \
    init_coll_creat_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_REPLA*/ \
    init_coll_repla_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_DROP*/ \
    init_coll_drop_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_INTEGRA*/ \
    init_coll_integra_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*COLE_RELOAD*/ \
    init_coll_reload_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV \
}

    //
    unsigned int INIT_INVA_SEND(session *seion, evdata *evdat);
    unsigned int init_colle_send(session *seion, evdata *evdat);

#define INIT_COLLE_SEND_TAB { \
    /*COLE_POST*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_STATU*/ \
    init_colle_send, init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_CREAT*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_REPLA*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_DROP*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_INTEGRA*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*COLE_RELOAD*/ \
    init_colle_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND \
}



#ifdef __cplusplus
}
#endif

#endif /* INITI_COLLECT_H */

