
/* 
 * File:   initi_constr.h
 * Author: James Xu
 *
 * Created on 2023.12.22, AM 10:54
 */

#ifndef INITI_CONSTR_H
#define INITI_CONSTR_H

#ifdef __cplusplus
extern "C" {
#endif

    // constr
    unsigned int INIT_INVA_RECV(session *seion, evdata *evdat);
    unsigned int init_enti_post_recv(session *seion, evdata *evdat);
    unsigned int init_enti_statu_recv(session *seion, evdata *evdat);
    unsigned int init_enti_creat_recv(session *seion, evdata *evdat);
    unsigned int init_enti_drop_recv(session *seion, evdata *evdat);
    unsigned int init_enti_updat_recv(session *seion, evdata *evdat);
    unsigned int init_enti_inser_recv(session *seion, evdata *evdat);
    unsigned int init_enti_searc_recv(session *seion, evdata *evdat);
    unsigned int init_enti_invok_recv(session *seion, evdata *evdat);

#define INIT_CONST_RECV_TAB { \
    /*POST*/ \
    init_enti_post_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*STATU*/ \
    init_enti_statu_recv, init_enti_statu_recv, init_enti_statu_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*CREATE*/ \
    init_enti_creat_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*DROP*/ \
    init_enti_drop_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*UPDATE*/ \
    init_enti_updat_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*INSERT*/ \
    init_enti_inser_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*SEARCH*/ \
    init_enti_searc_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*INVOKE*/ \
    init_enti_invok_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV \
}

    //
    unsigned int INIT_INVA_SEND(session *seion, evdata *evdat);
    unsigned int init_const_send(session *seion, evdata *evdat);

#define INIT_CONST_SEND_TAB { \
    /*POST*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*STATU*/ \
    init_const_send, init_const_send, init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*CREATE*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*DROP*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*UPDATE*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*INSERT*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*SEARCH*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*INVOKE*/ \
    init_const_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND \
}


#ifdef __cplusplus
}
#endif

#endif /* INITI_CONSTR_H */

