
/* 
 * File:   initi_query.h
 * Author: James Xu
 *
 * Created on 2023.12.22, AM 10:55
 */

#ifndef INITI_QUERY_H
#define INITI_QUERY_H

#ifdef __cplusplus
extern "C" {
#endif

    // query
    unsigned int INIT_INVA_RECV(session *seion, evdata *evdat);
    unsigned int init_quer_post_recv(session *seion, evdata *evdat);
    // init_quer_echo_recv
    unsigned int init_quer_statu_recv(session *seion, evdata *evdat);
    unsigned int init_quer_creat_recv(session *seion, evdata *evdat);
    unsigned int init_quer_drop_recv(session *seion, evdata *evdat);
    unsigned int init_quer_updat_recv(session *seion, evdata *evdat);
    unsigned int init_quer_inser_recv(session *seion, evdata *evdat);
    unsigned int init_quer_searc_recv(session *seion, evdata *evdat);
    unsigned int init_quer_invok_recv(session *seion, evdata *evdat);
    unsigned int init_quer_facto_recv(session *seion, evdata *evdat);

#define INIT_QUERY_RECV_TAB { \
    /*POST*/ \
    init_quer_post_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*STATU*/ \
    init_quer_statu_recv, init_quer_statu_recv, init_quer_statu_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*CREATE*/ \
    init_quer_creat_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*DROP*/ \
    init_quer_drop_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*UPDATE*/ \
    init_quer_updat_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*INSERT*/ \
    init_quer_inser_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*SEARCH*/ \
    init_quer_searc_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*INVOKE*/ \
    init_quer_invok_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, \
    /*FACTORY*/ \
    init_quer_facto_recv, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV, INIT_INVA_RECV \
}

    //
    unsigned int INIT_INVA_SEND(session *seion, evdata *evdat);
    unsigned int init_query_send(session *seion, evdata *evdat);

#define INIT_QUERY_SEND_TAB { \
    /*POST*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*STATU*/ \
    init_query_send, init_query_send, init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*CREATE*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*DROP*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*UPDATE*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*INSERT*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*SEARCH*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*INVOKE*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, \
    /*FACTORY*/ \
    init_query_send, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND, INIT_INVA_SEND \
}


#ifdef __cplusplus
}
#endif

#endif /* INITI_QUERY_H */

