#define TK_OR                               1
#define TK_AND                              2
#define TK_NOT                              3
#define TK_IS                               4
#define TK_MATCH                            5
#define TK_LIKE_KW                          6
#define TK_BETWEEN                          7
#define TK_IN                               8
#define TK_NE                               9
#define TK_EQ                              10
#define TK_GT                              11
#define TK_LE                              12
#define TK_LT                              13
#define TK_GE                              14
#define TK_ESCAPE                          15
#define TK_LP                              16
#define TK_RP                              17
#define TK_PLUS                            18
#define TK_MINUS                           19
#define TK_ID                              20
#define TK_CTIME_KW                        21
#define TK_ISNULL                          22
#define TK_NOTNULL                         23
#define TK_BITAND                          24
#define TK_BITOR                           25
#define TK_LSHIFT                          26
#define TK_RSHIFT                          27
#define TK_STAR                            28
#define TK_SLASH                           29
#define TK_REM                             30
#define TK_CONCAT                          31
#define TK_COLLATE                         32
#define TK_BITNOT                          33
#define TK_ON                              34
#define TK_STRING                          35
#define TK_NULL                            36
#define TK_FLOAT                           37
#define TK_BLOB                            38
#define TK_INTEGER                         39
#define TK_VARIABLE                        40
#define TK_JOIN_KW                         41
#define TK_COMMA                           42
// user define
#define TK_UPLUS                           65
#define TK_UMINUS                          66
#define TK_UINTEGER                        67
